### ISSUE TITLE
Removing frames to eval

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#119]
Hi there

If I wanted to do something simple by only evaluating the first 100 frames only in a subject ie. S9>Directions
By deleting all but the first 100 frames I get an error:

```
Experiment name: eval_human36m_vol_softmax_VolumetricTriangulationNet@09.12.2020-10:38:36
Traceback (most recent call last):
  File "train.py", line 483, in <module>
    main(args)
  File "train.py", line 476, in main
    one_epoch(model, criterion, opt, config, val_dataloader, device, 0, n_iters_total=0, is_train=False, master=master, experiment_dir=experiment_dir, writer=writer)
  File "train.py", line 176, in one_epoch
    for iter_i, batch in iterator:
  File "/home/jamal/anaconda3/envs/learnable_triangulation_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/jamal/anaconda3/envs/learnable_triangulation_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/jamal/anaconda3/envs/learnable_triangulation_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/jamal/anaconda3/envs/learnable_triangulation_1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/jamal/jknight_3TB/projects/test2/mvn/datasets/human36m.py", line 142, in __getitem__
    assert os.path.isfile(image_path), '%s doesn\'t exist' % image_path
AssertionError: ./data/human36m/processed/S9/Directions-1/imageSequence-undistorted/54138969/img_000101.jpg doesn't exist
```
Where in the code can I set the frame range to only consider frames 1 to 100?

Thanks

**Comment by shrubb** [comment]
Add something like `[:100]` [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/9d1a26ea893a513bdff55f30ecbfd2ca8217bf5d/train.py#L98)
