### ISSUE TITLE
Error wrapping 3D keypoints, bounding boxes and camera intrinsics together

### ISSUE THREAD

**Issue by jamalknight** [karfly/learnable-triangulation-pytorch#87]
I get an error in step 6 in the pre processing scripts section - Wrapping 3D keypoints, bounding boxes and camera intrinsics together:
(other than the warning of 'camera 54138969 isn't present in S11/Directions-2)

Command:
python3 generate-labels-npy-multiview.py ../../../data/human36m/ ../../../data/human36m/extra/una-dinosauria-data/ ../../../data/human36m/extra/bboxes-Human36M-GT.npy

Error:
Traceback (most recent call last):
  File "generate-labels-npy-multiview.py", line 58, in <module>
    cameras_params = h5py.File(os.path.join(una_dinosauria_root, 'cameras.h5'), 'r')
  File "/home/jamal/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/jamal/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../../../data/human36m/extra/una-dinosauria-data/cameras.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by shrubb** [comment]
Make sure you've extracted 'h36m.zip' at a previous step correctly so that `../../../data/human36m/extra/una-dinosauria-data/cameras.h5` exists.

**Comment by jamalknight** [comment]
Thats right. It was in a subfolder 'H36M' that was created when extracted.
Thanks
